console.log('o que acontece?')

const nome = 'Amanda'
console.log(nome)
try {
  nome = "Aline"
}
catch(erro) {
  console.error("erro capturado: " + erro)
}

console.log(' quando acontece algum erro')
